apiVersion: v1
kind: Service
metadata:
  namespace: node-app
  name: app-node-service
spec:
  selector:
    app: node
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer