---
apiVersion: v1
kind: ConfigMap
metadata: 
  namespace: {{ .Values.namespace }}
  name: app-configmap
data:
  NODE_ENV: "development"
  MONGO_USERNAME: {{ .Values.db.user }}
  MONGO_HOSTNAME: "app-db-service"
  MONGO_PORT: "27017"
  MONGO_DATABASE_NAME: {{ .Values.db.name }}
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.db.user }}
  MONGO_INITDB_DATABASE: {{ .Values.db.name }}
