---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: app-db-service
spec:
  ports:
    - targetPort: {{ .Values.db.port }}
      port: {{ .Values.db.port }}
      protocol: TCP
  selector:
    app: db