---
apiVersion: v1
kind: Secret
metadata: 
  namespace: {{ .Values.namespace }}
  name: app-secret
type: Opaque
data:
  MONGO_PASSWORD: {{ .Values.db.passwd }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.db.passwd }}