---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: node-app
  name: node-app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: standard-rwo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: node-app
  name: app-db-statefulset
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: app-db-pod
        image: mongo:4
        ports:
          - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: MONGO_INITDB_ROOT_PASSWORD
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: MONGO_INITDB_DATABASE
        volumeMounts:
        - name: node-app-volume
          mountPath: /data  # Mount point in the container
      
      volumes:
      - name: node-app-volume
        persistentVolumeClaim:
          claimName: node-app-pvc
