---
apiVersion: v1
kind: Service
metadata:
  namespace: node-app
  name: app-db-service
spec:
  ports:
    - targetPort: 27017
      port: 27017
      protocol: TCP
  selector:
    app: db